#!/bin/sh

# opendesktop autostart
# TODO:
# 2. download and cycle through wallpapers
# 3. brightness control
# 4. complete shortcuts
# 9. fix compositing; compton is crashing in alpine

XCS="randr compositor wallpaper volume locker shortcuts polkit"
stop(){
    for xc in $XCS; do
        sh ~/scripts/x.$xc.sh stop
    done
}
start(){
    for xc in $XCS; do
        sh ~/scripts/x.$xc.sh start
    done
}
case $i in
    stop)
        stop
        ;;
    *)
        stop
        start
        ;;
esac



