#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Util:assert_file_exists("dunst")
Shell.ln("$(pwd)/dunst/my", "~/.config/dunst")
