#!/usr/bin/env lua

require "luarocks.loader"

local Sh = require('minilib.shell')
local Ut = require('minilib.util')

local build_dir = os.getenv("HOME").."/xmonad-1"
local packs = {
	{
		name = "xmonad",
		ver  = "0.17.0",
		url  = "https://github.com/xmonad/xmonad/archive/refs/tags/v0.17.0.tar.gz",
	},
	{
		name = "xmonad-contrib",
		ver  = "0.17.0",
		url  = "https://github.com/xmonad/xmonad-contrib/archive/refs/tags/v0.17.0.tar.gz ",
	},
	{
		name = "xmobar",
		ver  = "0.42",
		url  = "https://github.com/jaor/xmobar/archive/refs/tags/0.42.tar.gz",
	},
}

function setup_xmonad()
	Sh.mkdir(build_dir)
	Sh.cp("$(pwd)/xmonad/xmonad-stack/*", build_dir)
	for _, p in ipairs(packs) do
		if not Sh.path_exists(build_dir.."/"..p.name) then
			local tar = "/tmp/"..p.name..".tar.gz"
			print("getting", p.name, p.ver, tar)
			Sh.wget(p.url, tar)
			Sh.sh(string.format("tar -xvzf %s -C %s", tar, build_dir))
			Sh.mv(
				string.format("%s/%s-%s", build_dir, p.name, p.ver),
				string.format("%s/%s", build_dir, p.name))
		end
	end
	Sh.sh(string.format("cd %s && stack install", build_dir))
end

function setup_xmonad_config()
	Sh.ln(build_dir, "~/.xmonad")
	Sh.ln("$(pwd)/xmonad/my/xmonad.hs", "~/.xmonad/xmonad.hs")
	Sh.sh("xmonad --recompile")
end

setup_xmonad_config()
