#!/usr/bin/env lua

require "luarocks.loader"

local Pr = require("minilib.process")
local Sh = require("minilib.shell")
local Ut = require("minilib.util")

Pr.new_listener()("pi", "weston", function()

    -- dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
    Ut:exec("dbus-launch --sh-syntax --exit-with-session")
    Ut:exec("dbus-update-activation-environment --systemd --all")

    -- key
    Ut:exec("thd --triggers triggerhappy/my/th.conf --deviceglob /dev/input/event* &")
    
    Ut:exec("lxpolkit &")
    
    Ut:exec("dunst &")
    Ut:exec("clipit &")
    Ut:exec("connman-gtk &")
    Ut:exec("mpd &")
    Ut:exec("VBoxClient --clipboard &")
    
    Ut:exec("weston-flower &")

end)
