#! /bin/sh

bspc monitor HDMI-A-0 -d VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox  desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Conky state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

sxhkd -c ~/.config/sxhkd/sharedrc ~/.config/sxhkd/
bspwmrc &

