#!/bin/sh

# opendesktop autostart
# TODO:
# 2. download and cycle through wallpapers
# 3. brightness control
# 4. complete shortcuts
# 9. fix compositing; compton is crashing in alpine

. ~/scripts/box_services.sh

compositer_stop
panel_stop
notifier_stop
monitor_stop
netapp_stop
clipboard_stop
volapp_stop
screenlocker_stop
shortcuts_stop
polkit_stop

launch init_start
launch compositer_start
launch wallpaper_start
launch panel_start
launch notifier_start
launch monitor_start
launch netapp_start
launch clipboard_start
launch volapp_start
launch screenlocker_start
launch shortcuts_start
launch polkit_start
