#!/usr/bin/env lua

require "luarocks.loader"

local Pr = require("minilib.process")
local Sh = require("minilib.shell")

Pr.new_listener()("pi", "weston", function()

    -- dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
    Sh.nohup("dbus-launch --sh-syntax --exit-with-session")
    Sh.nohup("dbus-update-activation-environment --systemd --all")

    -- sys key binder
    Sh.nohup("thd --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")

    Sh.nohup("lxpolkit")

    Sh.nohup("dunst")
    Sh.nohup("clipit")
    Sh.nohup("connman-gtk")
    
    Sh.nohup("conky -c ~/scripts/config/conky/simple/conky.conf 2>/dev/null 1>/dev/null")

    Sh.nohup("mpd")
    Sh.nohup("VBoxClient --clipboard")
end)
