#!/bin/sh

[ -d /tmp/run ] || mkdir /tmp/run

exe=$1
opt=$2

exe_name=$(basename $exe)
pid_file=/tmp/run/$exe_name.pid

if [ -f $pid_file ]; then
	pgrep -F $pid_file
	if [ ! $? -eq 1 ]; then
		echo "process [$exe_name] already running"
		exit
	fi
fi

cmd="$exe $opt &"
echo "> $cmd"

eval $cmd
echo $! > $pid_file
