#!/bin/sh

echo "serving $1 ..."

docker run -it \
	-p 8080:8080 \
	-v $1:/var/lib/spis/media \
	-v ~/.cache/spis:/var/lib/spis/data \
	-e SPIS_PROCESSING_RUN_ON_START=true \
	ghcr.io/gbbirkisson/spis
