#!/bin/sh

terms="alacritty kitty qterminal urxvtc urxvt gnome-terminal"
ivims="nvim vim"

getPath() {
	fs=$1
	for f in $fs; do
		if [ -f /usr/bin/$f ] || [ -f $HOME/.local/bin/$f ]; then
			echo $f
			break
		fi
	done
}

ivim=$(getPath $ivims)
term=$(getPath $terms)

cmd="$term -e $ivim $*"
echo ">> $cmd"
$cmd
exit 0
