#!/usr/bin/env lua
require "luarocks.loader"

local Sh = require('minilib.shell')

local cfg = {
	terms = {
		"alacritty",
		"stterm",
		"urxvt",
		"qterminal",
		"gnome-terminal",
		"xterm"
	},
	terms_cmd = {
		stterm = "stterm -f 'monospace:pixelsize=16' -g 96x40",
		urxvt = "urxvt",
		alacritty = "alacritty",
		qterminal = "qterminal",
		gnometerminal = "gnome-terminal",
		xterm = "xterm"
	},
	ivims = {
		"nvim",
		"vim"
	}
}

function select(fs)
	for _,f in ipairs(fs) do
		if Sh.file_exists(f) then
			return f
		end
	end
end

local ivim=select(cfg.ivims)
local term=select(cfg.terms)

local icmd=string.format("%s -e %s %s", cfg.terms_cmd[term], ivim, arg[1])
print(">>", icmd)

io.popen(icmd)
