#!/bin/sh

# Wayland stuff
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# IGPU_CARD=$(readlink -f /dev/dri/by-path/pci-0000:00:02.0-card)
# WLR_DRM_DEVICES="$IGPU_CARD" sway --unsupported-gpu

val=$(udevadm info -a -n /dev/dri/card1 | grep boot_vga | rev | cut -c 2)
WLR_DRM_DEVICES="/dev/dri/card$val" sway --unsupported-gpu
