#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

local init_opam = [[ 
   init_opam() {
    opam env
    if [ ! $? = 0 ]; then
        opam init
        eval $(opam env)
    fi
    if [ "$(which dune)" = "" ]; then
        opam install dune ounit2 ctypes ctypes-foreign stdio --yes
        eval $(opam env)
    fi
    eval $(opam env)
   }
   ]]

function setup_sourcebuild()
    local cmd = init_opam .. [[
        cd ~/
        init_opam
        if [ ! -d ~/fseer ]; then
            git clone https://github.com/bucketsize/fseer.git
        fi
        cd ~/fseer
        git checkout master
        git pull
        ./build
        ./build pack fseer
        ./build install fseer
    ]]
    Shell.assert_exec(cmd, "fseer sourcebuild")
end

function setup_prebuilt()
    local cmd = [[
        pkg=fseer.$(_arch).tar.gz
        cd /tmp
        wget https://github.com/bucketsize/fseer/releases/download/20220210/fseer.$(_arch).tar.gz 
        tar -xvzf $pkg -C ~/.local/bin
    ]]
    Shell.assert_exec(cmd, "fseer prebuilt")
end

setup_sourcebuild()

