#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Util = require('util')
--


local init_opam = [[ 
   init_opam() {
    opam env
    if [ ! $? = 0 ]; then
        opam init
        eval $(opam env)
    fi
    if [ "$(which dune)" = "" ]; then
        opam install dune ounit2 ctypes ctypes-foreign stdio --yes
        eval $(opam env)
    fi
    eval $(opam env)
   }
   ]]

function setup_sourcebuild()
    local cmd = init_opam .. [[
    cd ~/
    init_opam
    if [ ! -d ~/fseer ]; then
        git clone https://github.com/bucketsize/fseer.git
    fi
    cd ~/fseer
    git checkout master
    git pull
    ./build
    ./build pack fseer
    ./build install fseer
    ]]
    Util:exec(cmd)
end

function setup_prebuilt()
    local cmd = [[
    pkg=fseer.$(_arch).tar.gz
    cd /tmp
    wget https://github.com/bucketsize/fseer/releases/download/20220210/fseer.$(_arch).tar.gz 
    tar -xvzf $pkg -C ~/.local/bin
    ]]
    Util:exec(cmd)
end

setup_sourcebuild()

