#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.ln("$(pwd)/fontconfig/my", "~/.config/fontconfig")
Shell.ln("$(pwd)/../fonts", "~/.fonts")
