#!/usr/bin/env lua
require "luarocks.loader"

local Sh = require('minilib.shell')
local Ut = require('minilib.util')
local Home = os.getenv("HOME")

Sh.ln("$(pwd)/fontconfig/my", "~/.config/fontconfig")
local d = Sh.test(Home.."/.fonts")
if d == nil or d == "file" then
	Sh.rm(Home.."/.fonts")
	Sh.mkdir(Home.."/.fonts")
end

Sh.wget(
	"https://github.com/slavfox/Cozette/releases/download/v.1.13.0/cozette.otb",
	Home.."/.fonts/cozette.otb"
	)
Sh.wget(
	"https://github.com/slavfox/Cozette/releases/download/v.1.13.0/CozetteVector.otf",
	Home.."/.fonts/cozette_vector.otf"
	)
Sh.sh([[
	cd ~/.fonts
	mkfontdir
	mkfontscale
	xset +fp "$HOME/.fonts"
	xset fp rehash
	fc-cache -fv
	]])
