#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists("timedatectl")
Shell.exec([[
    sudo timedatectl set-timezone Asia/Kolkata
]])
