#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Util  = require('util')
local Shell = require('shell')
--

Util:assert_file_exists("timedatectl")
Shell.exec([[
    sudo timedatectl set-timezone Asia/Kolkata
]])
