#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Util:assert_file_exists("vim")
Shell.ln("~/scripts/config/vim/vimrc", "~/.vimrc")
Shell.ln("~/scripts/tvim", "~/.local/bin/tvim")
