#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("mpd")
Shell.file_exists ("mpc")

Shell.mkdir ("~/.mpd")
Shell.ln ("~/scripts/config/mpd/my", "~/.config/mpd")
print ("going to disable automatic root start of mpd:...")
Shell.sh("sudo systemctl disable mpd")
