#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("nvim")

Shell.ln ("$(pwd)/nvim/my","~/.config/nvim")
Shell.ln ("~/scripts/tvim","~/.local/bin/tvim")
