#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("mpv")
Shell.ln ("~/scripts/config/mpv/my", "~/.config/mpv")
