#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Util:assert_file_exists("picom")
Shell.ln ("~/scripts/config/picom/my", "~/.config/picom")
