#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("qutebrowser")
Shell.ln ("$(pwd)/qutebrowser/my","~/.config/qutebrowser")
