#!/usr/bin/env lua

require "luarocks.loader"

local Lr = require("minilib.process_listener")
local Sh = require("minilib.shell")

function autostart_weston()
    -- dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
    Sh.fork("dbus-launch --sh-syntax --exit-with-session")
    Sh.fork("dbus-update-activation-environment --systemd --all")

    -- sys key binder
    Sh.fork("thd --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")

    Sh.nohup("lxpolkit")

    Sh.fork("dunst")
    Sh.fork("clipit")
    Sh.fork("connman-gtk")
    
    Sh.fork("DISPLAY=:0 conky -c ~/scripts/config/conky/simple/conky.conf 2>/dev/null 1>/dev/null")

    Sh.fork("mpd")
    Sh.fork("VBoxClient --clipboard")
end

Lr.new_listener()
	.listen("pi", "weston", "start", function()
		print("pi, weston, start")
	end)
	.start()

