#!/usr/bin/env lua

require "luarocks.loader"

local Sh = require("minilib.shell")
local Ut = require("minilib.util")

local _HOME = os.getenv("HOME")
local wm = Ut:wminfo().wm:lower()
print("running org.autostart for "..wm)
local fn = loadfile(_HOME.."/.config/autostart/autostart_"..wm)
fn()
autostart()
