#!/usr/bin/env lua

require "luarocks.loader"

local Lr = require("minilib.process_listener")
local Sh = require("minilib.shell")
local Ut = require("minilib.util")

function autostart()
	Sh.sh([[
		xrdb -merge ~/.Xresources
		xhost +
		xsetroot -cursor_name left_ptr
		setxkbmap us
    
		# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
		dbus-launch --sh-syntax --exit-with-session
		dbus-update-activation-environment --systemd --all
	]])
	
    -- sys key binder
	Sh.forkonce("/usr/sbin/thd", "--triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")
	Sh.forkonce("mpd")
    Sh.forkonce("lxpolkit")
    Sh.forkonce("dunst")
    Sh.forkonce("VBoxClient", "--clipboard")
	Sh.forkonce("urxvtd", "-q -o -f")
	Sh.forkonce("picom")
	Ut.sleep(1)
	Sh.sh("~/.luarocks/bin/mxctl.control fun setup_video")
	Ut.sleep(1)
	Sh.sh("~/.luarocks/bin/mxctl.control fun applywallpaper")
    Sh.forkonce("tint2")
	Sh.forkonce("xmobar") --or conky 
    Sh.forkonce("flatpak run com.valvesoftware.Steam")


end

return autostart
