#!/usr/bin/env lua

require "luarocks.loader"

local Lr = require("minilib.process_listener")
local Sh = require("minilib.shell")
local Ut = require("minilib.util")

function autostart()
	Sh.sh([[
		xrdb -merge ~/.Xresources
		xhost +
		xsetroot -cursor_name left_ptr
		setxkbmap us
    
		# dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
		dbus-launch --sh-syntax --exit-with-session
		dbus-update-activation-environment --systemd --all
	]])

    -- sys key binder
	Sh.forkonce("thd --triggers", "~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")
	Sh.forkonce("mpd")
    Sh.forkonce("dunst")
	Sh.forkonce("urxvtd", "-q -o -f")
	Ut.sleep(1)
	Sh.forkonce("urxvtc")  -- to be safe
	Sh.forkonce("picom")
	Ut.sleep(1)
	Sh.sh("~/.luarocks/bin/mxctl.control fun setup_video")
	Ut.sleep(1)
	Sh.sh("~/.luarocks/bin/mxctl.control fun applywallpaper")
    Sh.forkonce("tint2")
	Sh.forkonce("conky") -- xmobar or conky or lemonbar
    Sh.forkonce("lxqt-policykit-agent")
    Sh.forkonce("lxqt-powermanagement")
    Sh.forkonce("VBoxClient --vmsvga")
    Sh.forkonce("VBoxClient --clipboard")
end

return autostart
