#!/usr/bin/env lua

require "luarocks.loader"

local Lr = require("minilib.process_listener")
local Sh = require("minilib.shell")
local Ut = require("minilib.util")

function autostart_weston()
	local env = "DISPLAY=:0 WAYLAND_DISPLAY=wayland-0 "	

    -- dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
    Sh.fork("dbus-launch --sh-syntax --exit-with-session")
	Sh.fork("dbus-update-activation-environment --systemd --all")

    -- sys key binder
    Sh.fork("thd --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")

    Sh.fork(env .. "lxpolkit")
    Sh.fork(env .. "dunst")
    Sh.fork(env .. "connman-gtk")
    Sh.fork(env .. "mpd")
    Sh.fork(env .. "VBoxClient --clipboard")
    Sh.fork(env .. "flatpak run com.valvesoftware.Steam")
    
	Sh.fork(env .. "conky") 

end

function autostart_openbox()
	local env = "DISPLAY=:0 "	
    
	-- dbus for dbus aware apps integration . ie pulseaudio, nautilus, firefox, dunst
    Sh.fork("dbus-launch --sh-syntax --exit-with-session")
    Sh.fork("dbus-update-activation-environment --systemd --all")


    -- sys key binder
    Sh.fork("thd --triggers ~/.config/triggerhappy/th.conf --deviceglob /dev/input/event*")
	
	Sh.fork("urxvtd '-q -o -f'")

	Sh.sh(env .. "~/.luarocks/bin/mxctl.control fun setup_video")
	Sh.sh(env .. "~/.luarocks/bin/mxctl.control fun applywallpaper")
	Sh.sh(env .. "setxkbmap us")
	Sh.sh(env .. "xsetroot -cursor_name left_ptr")

	Sh.fork(env .. "compton")
	Sh.fork(env .. "lxpolkit")
    Sh.fork(env .. "dunst")
    Sh.fork(env .. "tint2")
    Sh.fork(env .. "connman-gtk")
    Sh.fork(env .. "mpd")
    Sh.fork(env .. "VBoxClient --clipboard")
    Sh.fork(env .. "flatpak run com.valvesoftware.Steam")
	
	Sh.fork(env .. "conky") 

end

Lr.new_listener()
	.listen("pi", "weston", "start", autostart_weston)
	.listen("pi", "openbox", "start", autostart_openbox)
	.start()

