"call pathogen#infect() "moved to vundle

"{{{ vundle ---------------------------------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

Plugin 'VundleVim/Vundle.vim' "managed
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/syntastic'
Plugin 'itchyny/lightline.vim'
Plugin 'tpope/vim-surround'
Plugin 'vim-scripts/AutoComplPop'
Plugin 'SirVer/ultisnips'
Plugin 'artur-shaik/vim-javacomplete2'
Plugin 'sheerun/vim-polyglot'
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" }}} ---------------------------------------------------------------


syntax on

set history=100
set ruler
set showcmd
set number
set scrolloff=7               " Keep more lines of context
set sidescroll=1
set sidescrolloff=7
set title                     " Set xterm title
set columns=110
set autoindent  
set fileformats=unix,dos
set encoding=utf-8
set hlsearch                  " highlight search
set incsearch                 " incremental search
set noswapfile
set nowrap                    " don't wrap lines
set ignorecase                " ignore case when searching
set smartcase                 " ignore case if search pattern is all

set cursorline          " highlight current line
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup


autocmd FileType * set expandtab
autocmd FileType * set smartindent
autocmd FileType * set tabstop=2
autocmd FileType * set shiftwidth=2
autocmd FileType java set tabstop=4
autocmd FileType java set shiftwidth=4

colorscheme desert            " gui mode colorscheme

"---------------------------------------------------------------
" Map ctrl-movement keys to window switching
map <C-Up>    <C-w><Up>
map <C-Down>  <C-w><Down>
map <C-Right> <C-w><Right>
map <C-Left>  <C-w><Left>

" Switch to alternate file
map <C-Tab> :bnext<cr>
map <C-S-Tab> :bprevious<cr>

" Note: commands
" ctrl-w-v    vertical split
" ctrl-w-s    horizontal split
" ctrl-w-w    cycle split buffers
"---------------------------------------------------------------

"---------------------------------------------------------------
" complete as you type
" http://vim.wikia.com/wiki/Make_Vim_completion_popup_menu_work_just_like_in_an_IDE
set completeopt=longest,menuone
inoremap <expr> <C-n> pumvisible() ? '<C-n>' :
  \ '<C-n><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
inoremap <expr> <M-,> pumvisible() ? '<C-n>' :
  \ '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
"---------------------------------------------------------------

"---------------------------------------------------------------
"using nailgun - <C-X><C-O> 
" https://github.com/paretje/javacomplete
"let g:nailgun_port='2113'
"let g:javacomplete_ng='ng-nailgun'
"---------------------------------------------------------------

"---------------------------------------------------------------
"vim-antr 
" autocmd Filetype java setlocal omnifunc=antr#ListSymbols
"--------------------------------------------------------------- 

"---------------------------------------------------------------
"vim-JavaComplete2 
autocmd FileType java setlocal omnifunc=javacomplete#Complete
"autocmd FileType java setlocal completefunc=javacomplete#CompleteParamsInfo
" To enable inserting class imports with F4, add:
nmap <F4> <Plug>(JavaComplete-Imports-Add)
imap <F4> <Plug>(JavaComplete-Imports-Add)
" To add all missing imports with F5:
nmap <F5> <Plug>(JavaComplete-Imports-AddMissing)
imap <F5> <Plug>(JavaComplete-Imports-AddMissing)
" To remove all missing imports with F6:
nmap <F6> <Plug>(JavaComplete-Imports-RemoveUnused)
imap <F6> <Plug>(JavaComplete-Imports-RemoveUnused)
"--------------------------------------------------------------- 


"---------------------------------------------------------------
" UltiSnips: needs vim-snippets to work 
" https://github.com/sirver/ultisnips
" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"
" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"
"--------------------------------------------------------------- 
