#!/bin/sh

# opendesktop autostart
# TODO:
# 2. download and cycle through wallpapers
# 3. brightness control
# 4. complete shortcuts
# 9. fix compositing; compton is crashing in alpine

XCS="randr compositor wallpaper panel notifier monitor network clipboard volume locker shortcuts polkit"
stopAll(){
    for xc in $XCS; do
        sh ~/scripts/x.$xc.sh stop
    done
}
startAll(){
    for xc in $XCS; do
        sh ~/scripts/x.$xc.sh start
    done
}
case $i in
    stop)
        stopAll
        ;;
    *)
        stopAll
        startAll
        ;;
esac



