#!/bin/sh

# opendesktop autostart
# TODO:
# 2. download and cycle through wallpapers
# 3. brightness control
# 4. complete shortcuts
# 9. fix compositing; compton is crashing in alpine

stopAll(){
	killall picom
	killall dunst
	killall tint2
	killall conky
	killall lxpolkit
	killall lxclipboard
	killall skhkd
	xautolock -exit
	killall light-locker
}
startAll(){
	picom &
	dunst &
	tint2 &
	conky &
	lxpolkit &
	lxclipboard &
	sxhkd &
	xautolock \
		-time 5 -locker "~/scripts/sys_ctl/ctl.lua cmd scr_lock" \
		-killtime 10 -killer "notify-send -u critical -t 10000 -- 'Killing system ...'" \
		-notify 30 -notifier "notify-send -u critical -t 10000 -- 'Locking system ETA 30s ...'" &
	~/scripts/sys_ctl/ctl.lua cmd scr_lock_on_lid &
	~/scripts/xdg/x.wallpaper.sh &
}

case $i in
    stop)
        stopAll
        ;;
    *)
        stopAll
        startAll
        ;;
esac



