#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util  = require('minilib.util')

Shell.file_exists("xrdb")
Shell.ln("$(pwd)/Xresources/my","~/.config/xresources.d")
Shell.ln("$(pwd)/Xresources/my/Xresources","~/.Xresources")
Shell.ln("$(pwd)/Xresources/my/xinitrc","~/.xinitrc")
