#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')


Shell.file_exists("xrdb")
Shell.file_exists("sed")
Shell.ln("$(pwd)/Xresources/my","~/.config/xresources.d")
Shell.cp("$(pwd)/Xresources/my/.Xresources","~/.Xresources")
Shell.exec([[
        sed -i "s|__home|$HOME|g" ~/.Xresources
]])
