#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Util  = require('util')
local Shell = require('shell')
--

Util:assert_file_exists("xrdb")
Util:assert_file_exists("sed")
Shell.cp("~/scripts/config/Xresources/my/.Xresources","~/.Xresources")
Shell.exec([[
        sed -i "s|__home|$HOME|g" ~/.Xresources
]])
