#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Shell = require('shell')
--

-- note; only works on arch linux
Shell.ln ("$(pwd)/chromium/my/chromium-flags.conf", "~/.config/chromium-flags.conf")
Shell.ln ("$(pwd)/chromium/my/chromium-accel.desktop", "~/.local/share/applications/chromium-accel.desktop")
