#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

-- note; only works on arch linux
Shell.ln ("$(pwd)/chromium/my/chromium-flags.conf", "~/.config/chromium-flags.conf")
Shell.ln ("$(pwd)/chromium/my/chromium-accel.desktop", "~/.local/share/applications/chromium-accel.desktop")
