#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Shell = require('shell')
--

Shell.cp("$(pwd)/gtk/.gtkrc-2.0", "~/.gtkrc-2.0")

Shell.md("~/.config/gtk-3.0")
Shell.cp("$(pwd)/gtk/gtk.css", "~/.config/gtk-3.0/gtk.css")
Shell.cp("$(pwd)/gtk/settings.ini", "~/.config/gtk-3.0/settings.ini")

