#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("sxhkd")
Shell.ln ("~/scripts/config/sxhkd/my","~/.config/sxhkd")
