#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("openbox")
Shell.file_exists ("obconf")

Shell.ln ("$(pwd)/openbox/my", "~/.config/openbox")
Shell.ln ("~/.config/autostart/autostart", "$(pwd)/openbox/my/autostart")

-- theme
Shell.mkdir ("~/.themes")
Shell.sh([[
	cd ~/.themes
	if [ ! -d nord-openbox-theme ]; then 
		git clone https://gitlab.com/the-zero885/nord-openbox-theme.git
	fi
	]])

