#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists ("openbox")
Shell.file_exists ("obconf")

Shell.ln ("$(pwd)/openbox/my", "~/.config/openbox")

-- theme
Shell.mkdir ("~/.themes")

-- TODO : use release tar.gz
Shell.sh([[
	cd ~/.themes
	if [ ! -d nord-openbox-theme ]; then 
		git clone https://gitlab.com/the-zero885/nord-openbox-theme.git
	fi
	if [ ! -d OpenBox-Themes ]; then 
		git clone https://github.com/mylesthaiss/OpenBox-Themes.git
		cp -a OpenBox-Themes/Zukit* ./
	fi
	if [ ! -d arc-openbox ]; then 
		git clone https://github.com/dglava/arc-openbox.git
		cp -a arc-openbox/* ./
	fi
	]])

