#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Util:assert_file_exists ("openbox")
Util:assert_file_exists ("obconf")

Shell.ln ("$(pwd)/openbox/my", "~/.config/openbox")
Shell.mkdir ("~/.themes")
Shell.ln ("$(pwd)/openbox/themes/Tenebris/", "~/.themes/Tenebris")
