#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Util:assert_file_exists ("tint2")
Shell.ln ("~/scripts/config/tint2/dashy","~/.config/tint2")
