#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists("xmobar")

Shell.ln("$(pwd)/xmobar/my", "~/.config/xmobar")

