#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Util  = require('util')
local Shell = require('shell')
--

Util:assert_file_exists("weston")
Util:assert_file_exists("foot")
Util:assert_file_exists("wofi")

Shell.ln("$(pwd)/weston/my/weston.ini"
    , "~/.config/weston.ini")

Shell.assert_exec([[
    [ -d /opt/sbin ] || sudo mkdir -p /opt/sbin

    sudo ln -s $(pwd)/../autostartd /opt/sbin/autostartd
    sudo ln -s $(pwd)/weston/my/weston-autostart.service \
        /etc/systemd/user/weston-autostart.service
    
    systemctl --user daemon-reload
    systemctl --user enable weston-autostart.service 
    ]])

