xrdb -merge ~/.Xresources
xhost +

export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11
export XDG_CURRENT_DESKTOP=GNOME-Classic:GNOME
export GNOME_SHELL_SESSION_MODE=classic

~/scripts/config/autostart.sh

#exec gnome-session
#exec openbox-session
exec i3
