#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

function setup_sourcebuild()
    local cmd = string.format([[
    . ../common.sh
    echo "setup $(pwd) ..."

    checkpkgs "git libssl make urxvt xrandr fzy wmctrl pactl feh"
    githubfetch bucketsize/minilib
    githubfetch bucketsize/mxctl

    ipwd=$(pwd)
    LIBDIR=/usr/lib/%s-linux-gnu
    cd ~/minilib && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR
    [ $? = 0 ] || exit 22
    cd ~/mxctl && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR 
    [ $? = 0 ] || exit 22
    cd $ipwd

    if [ -d ~/.config/mxctl ]; then
        echo "[~/.config/mxctl] already present"
    else
        createdir ~/.config/mxctl
        cp ~/scripts/config/mxctl/my/config ~/.config/mxctl/
    fi
    ]], Shell.arch())
    Shell.assert_exec(cmd, "failed")
end

return setup_sourcebuild()
