#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Shell = require('shell')
--

function setup_sourcebuild()
    local cmd = [[
    . ../common.sh
    echo "setup $(pwd) ..."

    checkpkgs "git libssl make urxvt xrandr fzy wmctrl pactl feh"
    githubfetch bucketsize/minilib
    githubfetch bucketsize/mxctl

    ipwd=$(pwd)
    LIBDIR=/usr/lib/$(_arch)-linux-gnu
    cd ~/minilib && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR
    [ $? = 0 ] || exit 22
    cd ~/mxctl && luarocks make --local CRYPTO_LIBDIR=$LIBDIR OPENSSL_LIBDIR=$LIBDIR 
    [ $? = 0 ] || exit 22
    cd $ipwd

    if [ -d ~/.config/mxctl ]; then
        echo "[~/.config/mxctl] already present"
    else
        createdir ~/.config/mxctl
        cp ~/scripts/config/mxctl/my/config ~/.config/mxctl/
    fi
    ]]
    Shell.assert_exec(cmd, "failed")
end

return setup_sourcebuild()
