#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.assert_file_exists ("qt5ct")
Shell.ln ("$(pwd)/qt5ct/my","~/.config/qt5ct")
