#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.file_exists("triggerhappy")
Shell.ln("$(pwd)/triggerhappy/my", "~/.config/triggerhappy")
