#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')


if not Shell.file_exists("~/.local/bin/ympd") then
    local cmd = string.format([[
        if [ -d ~/ympd ]; then
            cd ~/ympd
            git pull
        else
            git clone https://github.com/notandy/ympd.git
            cd ~/ympd
        fi
        export LIBDIR=/usr/lib/$%s-linux-gnu
        make ympd
        strip ympd
        cp -vf ympd ~/.local/bin/
    ]], Shell.arch())
    Shell.exec(cmd)
end
