#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Util = require('util')
local Shell = require('shell')
--

function setup_sourcebuild()
    Util:assert_pkg_exists("xcb")
    Util:assert_pkg_exists("xcb-randr")
    Util:assert_pkg_exists("xft")
    Util:assert_pkg_exists("x11-xcb")
    Util:assert_pkg_exists("xcb-xinerama")
    local cmd = string.format([[
        if [ -d ~/lemonbar-xft ]; then
            cd ~/lemonbar-xft
            git pull
        else
            cd ~/
            git clone https://gitlab.com/protesilaos/lemonbar-xft.git
            cd ~/lemonbar-xft
        fi
        make
        tar -czf lemonbar.%s.tar.gz lemonbar
        cp -fv lemonbar ~/.local/bin/
        ]], Shell.arch())
    Shell.assert_exec(cmd, "failed")
end

function setup_prebuilt()
    local cmd = [[
        pkg=lemonbar.$(arch).tar.gz
        cd /tmp
        wget https://www.dropbox.com/s/hxuj4yz0x0vvrfj/$pkg 
        tar -xvzf $pkg -C ~/.local/bin
        ]]
    Shell.assert_exec(cmd, "failed")
end

setup_sourcebuild()
