#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Shell.assert_file_exists("pipewire")

local cmd = [[
#sessf=/etc/pipewire/media-session.d/with-pulseaudio
sessf=$HOME/.config/pipewire-media-session/with-pulseaudio
servd=$HOME/.config/systemd/user

if [ ! -f $sessf ] ; then
    echo "installing pulse session [with-pulseaudio] ..."
	if [ ! -d "$HOME/.config/pipewire-media-session" ]; then
		mkdir -p $HOME/.config/pipewire-media-session
	fi
    touch $sessf
fi

if [ "$(ls $servd/pipewire-pulse.*)" = "" ]; then
    echo "installing pulse service ..."
    cp /usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.* $servd/
fi

systemctl --user daemon-reload
systemctl --user --now enable pipewire pipewire-pulse
systemctl --user --now disable pulseaudio.service pulseaudio.socket
systemctl --user mask pulseaudio
]]

Shell.sh(cmd)
