#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')

-- Shell.ln("$(pwd)/autostart/my/autostartd", "~/.local/bin/autostartd")
    
-- Shell.mkdir("~/.config/systemd/user")
-- Shell.sh([[
-- 	ln -sfv $(pwd)/autostart/my/autostart.service ~/.config/systemd/user/autostart.service
--     systemctl --user daemon-reload
--     systemctl --user enable autostart.service 
--     ]])

Shell.ln("$(pwd)/autostart/my/autostart_openbox"
	, "~/.local/bin/autostart_openbox")
Shell.ln("$(pwd)/autostart/my/autostart_weston"
	, "~/.local/bin/autostart_weston")
Shell.ln("$(pwd)/autostart/my/autostart.lua"
	, "~/.local/bin/autostart")
