#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

Util:assert_file_exists("foot")
Shell.ln("$(pwd)/foot/my", "~/.config/foot")
