#! /bin/sh

# jvm apps
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

pgrep -x sxhkd > /dev/null \
	|| sxhkd -c ~/.config/sxhkd/sharedrc ~/.config/sxhkd/bspwmrc &

pgrep -x lemonbar > /dev/null \
	|| ~/.luarocks/bin/frmad.lemonbar_out | lemonbar \
	-f "Fira Code:size=10" \
	-f "Font Awesome 5 Free:size=10" \
	-F "#dddddd" \
	-B "#87000000" &

pgrep -x tint2 > /dev/null \
	|| tint2 &

bspc monitor -d 0 1 2 3 4 5 6 7 8 9
bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5001
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer       true
bspc config auto_alternate              true

bspc rule -a Chromium desktop=2 private=on
bspc rule -a Firefox  desktop=2 private=on
bspc rule -a Gimp desktop=8 state=floating follow=on
bspc rule -a Gpicview state=floating
bspc rule -a Qiv state=floating
bspc rule -a Mpv state=floating
bspc rule -a Conky state=floating
bspc rule -a Steam desktop=7 state=floating follow=on
bspc rule -a '*:*:Popeye' state=floating focus=on
bspc rule -a '*:*:Tmpc' state=floating focus=on
bspc rule -a Tint2 border=off manage=off
bspc rule -a Libreoffice state=monocle
