#! /bin/sh

bspc monitor HDMI-A-0 -d VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Chromium desktop='^2'
bspc rule -a Firefox  desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gpicview state=floating
bspc rule -a Qiv state=floating
bspc rule -a mpv state=floating
bspc rule -a Conky state=floating
bspc rule -a Steam desktop='^7' state=floating follow=on
bspc rule -a Alacritty:Popeye state=floating focus=on

# jvm apps
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd -c ~/.config/sxhkd/sharedrc ~/.config/sxhkd/bspwmrc &

~/.luarocks/bin/frmad.lemonbar_out | lemonbar \
	-f "Fira Sans Condensed:size=10" \
	-f "Font Awesome 5 Free:size=10" \
	-F "#aaaaaa" \
	-B "#000000" &

tint2 &
