#!/usr/bin/env lua
--
package.path = os.getenv("HOME")..'/scripts/?.lua;' .. package.path
local Shell = require('shell')
--

Shell.md ("~/.local/bin")

Shell.ln ("$(pwd)/lspd/my/lspd-ocaml", "~/.local/bin/lspd-ocaml")
Shell.ln ("$(pwd)/lspd/my/lspd-java", "~/.local/bin/lspd-java")
