#!/usr/bin/env lua
require "luarocks.loader"

local Shell = require('minilib.shell')
local Util = require('minilib.util')

-- note; only works on arch linux
Shell.ln ("$(pwd)/firefox/my/user.js", "~/.mozilla/firefox/hlnn94f7.default-esr/user.js")
