#!/usr/bin/env lua
require "luarocks.loader"

local Sh = require('minilib.shell')
local Ut = require('minilib.util')
local Pr = require('minilib.process')

Pr.pipe()
	.add(Sh.exec("find -L ~/.mozilla/  -name \"xulstore.json\" | grep -v backup"))
	.add(Sh.echo())
	.add(function (x)
		if x then
			local f, p = Sh.split_path(x)
			Sh.cp ("$(pwd)/firefox/my/user.js", p)
		end
	end)
	.run()
